version: '3'
services:
    notifications-queue:
        build: ./adapted-rabbitmq
        restart: always

        # Uncomment this for RabbitMQ debug/management
        #ports:
          #- "15672:15672"
          #- "5672:5672"

    notifications-push-service:
        build: ./job-scheduler-notification-push-service
        restart: always
        depends_on:
            - notifications-queue
        ports:
            - "9030:9030"

    job-scheduler-front-end:
        build: ./job-scheduler-frontend
        restart: always
        depends_on:
            - job-scheduler-server
        ports:
            - "3000:3000"

    job-scheduler-server:
        build: ./job-scheduler-server
        restart: always
        depends_on:
            - notifications-push-service
        ports:
            - "5000:5000"
